# Generated by Django 3.1.5 on 2021-01-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Ссылки', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.RemoveField(
            model_name='link',
            name='out_link',
        ),
        migrations.AddField(
            model_name='link',
            name='old_link',
            field=models.URLField(blank=True, verbose_name='старая ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='new_link',
            field=models.CharField(max_length=10, verbose_name='новая ссылка'),
        ),
    ]
